// <auto-generated />
using System;
using DoAnLTW.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnLTW.Migrations
{
    [DbContext(typeof(DbContext_TuiXach))]
    [Migration("20261004131152_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnLTW.Models.ChiTietDonHang", b =>
                {
                    b.Property<Guid>("maDH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("maTui")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("donGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("soLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("thanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("maDH", "maTui");

                    b.HasIndex("maTui");

                    b.ToTable("ChiTietDonHangs");
                });

            modelBuilder.Entity("DoAnLTW.Models.ChiTietGioHang", b =>
                {
                    b.Property<Guid>("maGioHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("maTui")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("soLuong")
                        .HasColumnType("int");

                    b.HasKey("maGioHang", "maTui");

                    b.HasIndex("maTui");

                    b.ToTable("ChiTietGioHangs");
                });

            modelBuilder.Entity("DoAnLTW.Models.DonHang", b =>
                {
                    b.Property<Guid>("maDH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("diaChiNhan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("maKH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ngayDat")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("tongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("trangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("maDH");

                    b.HasIndex("maKH");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("DoAnLTW.Models.GioHang", b =>
                {
                    b.Property<Guid>("maGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("maKH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ngayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("maGioHang");

                    b.HasIndex("maKH")
                        .IsUnique();

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("DoAnLTW.Models.HinhAnhTui", b =>
                {
                    b.Property<Guid>("maHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("laAnhChinh")
                        .HasColumnType("bit");

                    b.Property<Guid>("maTui")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tenHinhAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("thuTu")
                        .HasColumnType("int");

                    b.HasKey("maHinhAnh");

                    b.HasIndex("maTui");

                    b.ToTable("HinhAnhTuis");
                });

            modelBuilder.Entity("DoAnLTW.Models.KhachHang", b =>
                {
                    b.Property<Guid>("maKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("diaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("hoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("matk")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("sdt")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("maKH");

                    b.HasIndex("matk")
                        .IsUnique();

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("DoAnLTW.Models.KhuyenMai", b =>
                {
                    b.Property<Guid>("maKM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ngayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<double>("phanTramGiam")
                        .HasColumnType("float");

                    b.Property<string>("tenKM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("maKM");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("DoAnLTW.Models.LoaiTui", b =>
                {
                    b.Property<Guid>("maLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("maLoai");

                    b.ToTable("LoaiTuis");
                });

            modelBuilder.Entity("DoAnLTW.Models.TaiKhoan", b =>
                {
                    b.Property<Guid>("maTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("matKhau")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("tenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("vaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maTK");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("DoAnLTW.Models.ThuongHieu", b =>
                {
                    b.Property<Guid>("maThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tenThuongHieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("maThuongHieu");

                    b.ToTable("ThuongHieus");
                });

            modelBuilder.Entity("DoAnLTW.Models.TuiXach", b =>
                {
                    b.Property<Guid>("maTui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("donGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("maKM")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("maLoai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("maThuongHieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("moTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("soLuong")
                        .HasColumnType("int");

                    b.Property<string>("tenTui")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("maTui");

                    b.HasIndex("maKM");

                    b.HasIndex("maLoai");

                    b.HasIndex("maThuongHieu");

                    b.ToTable("TuiXachs");
                });

            modelBuilder.Entity("DoAnLTW.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("DoAnLTW.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("maDH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnLTW.Models.TuiXach", "TuiXach")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("maTui")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("TuiXach");
                });

            modelBuilder.Entity("DoAnLTW.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("DoAnLTW.Models.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("maGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnLTW.Models.TuiXach", "TuiXach")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("maTui")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("TuiXach");
                });

            modelBuilder.Entity("DoAnLTW.Models.DonHang", b =>
                {
                    b.HasOne("DoAnLTW.Models.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("maKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DoAnLTW.Models.GioHang", b =>
                {
                    b.HasOne("DoAnLTW.Models.KhachHang", "KhachHang")
                        .WithOne("GioHang")
                        .HasForeignKey("DoAnLTW.Models.GioHang", "maKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DoAnLTW.Models.HinhAnhTui", b =>
                {
                    b.HasOne("DoAnLTW.Models.TuiXach", "TuiXach")
                        .WithMany("HinhAnhTuis")
                        .HasForeignKey("maTui")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TuiXach");
                });

            modelBuilder.Entity("DoAnLTW.Models.KhachHang", b =>
                {
                    b.HasOne("DoAnLTW.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("DoAnLTW.Models.KhachHang", "matk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DoAnLTW.Models.TuiXach", b =>
                {
                    b.HasOne("DoAnLTW.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("TuiXachs")
                        .HasForeignKey("maKM")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DoAnLTW.Models.LoaiTui", "LoaiTui")
                        .WithMany("TuiXachs")
                        .HasForeignKey("maLoai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoAnLTW.Models.ThuongHieu", "ThuongHieu")
                        .WithMany("TuiXachs")
                        .HasForeignKey("maThuongHieu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhuyenMai");

                    b.Navigation("LoaiTui");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("DoAnLTW.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("DoAnLTW.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("DoAnLTW.Models.KhachHang", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("DoAnLTW.Models.KhuyenMai", b =>
                {
                    b.Navigation("TuiXachs");
                });

            modelBuilder.Entity("DoAnLTW.Models.LoaiTui", b =>
                {
                    b.Navigation("TuiXachs");
                });

            modelBuilder.Entity("DoAnLTW.Models.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DoAnLTW.Models.ThuongHieu", b =>
                {
                    b.Navigation("TuiXachs");
                });

            modelBuilder.Entity("DoAnLTW.Models.TuiXach", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("HinhAnhTuis");
                });
#pragma warning restore 612, 618
        }
    }
}
